### ISSUE TITLE
Multiple Filters

### ISSUE THREAD

**Issue by bradmcnay** [cryptk/opsy#18]
To be able to filter on multiple items, such as select multiple sensu-api endpoints for your data center or only show alerts relating to MySQL being not running. Additionally, having a reverse filter such as NOT staging AND NOT development.

**Comment by cryptk** [comment]
The filtering that is being added to the api should be able to support this fairly easily

**Comment by cryptk** [comment]
we should be able to send in multiple items to filter for, as well as inverted selections (not).

EX: ?check.name=mysql-not-running,datacenter=!FOO

The above would return all items where the check name is 'mysql-not-running' except for the ones in the datacenter named FOO

**Comment by testeddoughnut** [comment]
Done.

**Comment by testeddoughnut** [comment]
API done.
