### ISSUE TITLE
Configure dashboards based on the configuration of other dashboards

### ISSUE THREAD

**Issue by cryptk** [cryptk/opsy#51]
By giving a dashboard configuration such as:

``` [Admin]
dashboard = !Support

[Support]
checkname = mysqld-not-running,redis-memory-usage
```

This should be semantically identical to the following:

``` [Admin]
checkname = !mysqld-not-running,!redis-memory-usage

[Support]
checkname = mysqld-not-running,redis-memory-usage
```

**Comment by testeddoughnut** [comment]
Closing this for now, might revisit this feature in the future if we rework how dashboards are generated. Adds too much complexity for the time being.
