### ISSUE TITLE
Add option to color the entire line of the alert

### ISSUE THREAD

**Issue by derekmoyes** [cryptk/opsy#59]
Once dashboard options are configurable, please add an option for the entire event row to be the color of the status of the alert. 

Although I do like the flag, I also preferred the entire row highlighted in color. :-) 

Alternatively, the main header of the page could change color to the "highest" alert color, so that it would be very obvious if your currently configured dashboard had any CRITICAL alerts.

**Comment by cryptk** [comment]
The leftmost td in the row will be colored to indicate the event severity, we are reserving coloring the full row to indicate other metadata about the event in the future (such as events that are claimed, events that have a scheduled maintenance, etc).
