### ISSUE TITLE
TODO: make sure that filtering for events with hide_silenced=1 takes into account silenced clients

### ISSUE THREAD

**Issue by testeddoughnut** [cryptk/opsy#63]

**Comment by cryptk** [comment]
Rather than setting hide_silenced to 1 causing everything that has a stash to be hidden, what if we can do the following:

hide_silenced=checks,clients

This would allow us to show/hide the stashed checks and clients separately.

**Comment by testeddoughnut** [comment]
Good idea, I'll work on that on Monday

**Comment by cryptk** [comment]
Cool, I went ahead and coded the front-end to work that way, so once you
get the API updated it will start working.

**Comment by testeddoughnut** [comment]
Fixed with #69
